version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Solo este puerto necesario
    environment:
      - SERVICES=lambda,apigateway,dynamodb,s3,ssm,cloudformation,iam,events
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  nodejs-app:
    build: .
    ports:
      - "9229:9229"
    volumes:
      - .:/app
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - LOCALSTACK_ENDPOINT=http://localstack:4566
